config/routes.rb
Rails.application.routes.draw do
  resources :chord_sequences
  resources :chords
  devise_for :users
  resources :tonalities

  root 'main#index'

  resources :api do
    collection do
      get :get_test_chords
      get :get_tonalities

      post :get_chords
      post :get_chords_new
    end
  end

end

app/models/chord.rb
class Chord < ActiveRecord::Base
  has_many :child_chords, class_name: "Chord", foreign_key: "parent_chord_id"
  belongs_to :parent_chord, class_name: "Chord"

  attr_accessor :soprano_stage
  attr_accessor :alt_stage
  attr_accessor :tenor_stage
  attr_accessor :bass_stage
  attr_accessor :soprano_octave

  def for_tonality(tonality)
    self.soprano_stage = tonality.stages.find{|s| s.index == self.soprano}
    self.alt_stage = tonality.stages.find{|s| s.index == self.alt}
    self.tenor_stage = tonality.stages.find{|s| s.index == self.tenor}
    self.bass_stage = tonality.stages.find{|s| s.index == self.bass}
    self
  end

  def with_soprano_octave(soprano_octave)
    self.soprano_octave = soprano_octave.to_i
    self
  end

  def convert
    r = {}
    octave = self.soprano_octave
    r[:soprano_note] = self.soprano_stage.get_note(octave)
    octave -= 1 if self.alt_stage >= self.soprano_stage
    r[:alt_note] = self.alt_stage.get_note(octave)
    octave -= 1 if self.tenor_stage >= self.alt_stage
    octave = 4 if octave > 4 # Хак, что делается октава меньше для корректного отображения
    r[:tenor_note] = self.tenor_stage.get_note(octave)
    octave -= 1 if self.bass_stage >= self.tenor_stage
    r[:bass_note] = self.bass_stage.get_note(octave)
    r[:name] = self.name
    r
  end

  def as_json(options=nil)
    result = super(options)
    result.merge(self.convert)
  end
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  load_and_authorize_resource
  before_action :set_parent_chords

  def index
    @chords = Chord.all.order(:name)
    render :index
  end

  def new
    render :new
  end

  def create
    if @chord.save
      redirect_to chords_path
    else
      render :new
    end
  end

  def update
    if @chord.update_attributes(chord_params)
      redirect_to chords_path
    else
      render :edit
    end
  end

  def destroy
    @chord.destroy
    redirect_to chords_path
  end

  private

  def set_parent_chords
    @parent_chords = Chord.where(:parent_chord_id => nil)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chord_params
    params.require(:chord).permit(:name, :soprano, :alt, :tenor, :bass, :position, :parent_chord_id)
  end
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/views/chords/_form.html.slim
= simple_form_for(@chord) do |f|
  - if @chord.errors.any?
    #error_explanation
      h2 = "#{pluralize(@chord.errors.count, "error")} prohibited this chord from being saved:"
      ul
        - @chord.errors.full_messages.each do |message|
          li = message
  .row
    .col-md-6
      .form-group
        =  f.input :name, :label => false, :input_html => { :placeholder => "Название аккорда",:class => "form-control" }
      .form-group
        = f.input :soprano, :label => 'Сопрано', :input_html => {:placeholder => "Сопрано", :class => "form-control"}
      .form-group
        = f.input :alt, :label => 'Альт', :input_html => {:placeholder => "Альт", :class => "form-control"}
      .form-group
        = f.input :tenor, :label => 'Тенор', :input_html => {:placeholder => "Тенор", :class => "form-control"}
      .form-group
        = f.input :bass, :label => 'Бас', :input_html => {:placeholder => "Бас", :class => "form-control"}
      .form-group
        = f.collection_radio_buttons :position,
                [[true, 'Широкое'], [false, 'Тесное']],
                :first,
                :last,
                :item_wrapper_class => 'radio-inline'
      .form-group
        =  f.input :parent_chord_id, :label => 'Функция', :collection => @parent_chords, :input_html => {:class => "form-control"}
      .btn-group
          = f.submit 'Сохранить', :class => 'btn btn-primary'
          = link_to 'Назад', chords_path, :class => 'btn btn-default'

app/views/chords/edit.html.slim
h1 Редактирование аккорда

== render 'form'

app/views/chords/index.html.slim
h1 Аккорды

= link_to 'Новый аккорд', new_chord_path
table.table
  thead
    tr
      th Имя
      th Ступени
      th Расположение
      th
      th

  tbody
    - @chords.each do |chord|
      tr
        td = chord.name
        td = "Бас:#{chord.bass}, Тенор:#{chord.tenor}, Альт:#{chord.alt}, Сопрано:#{chord.soprano}"
        td = chord.position.nil? ? 'Не указано' : chord.position ? 'Широкое' : 'Тесное'
        td = link_to 'Редактировать', edit_chord_path(chord)
        td = link_to 'Удалить', chord, data: { confirm: 'Вы уверены?' }, method: :delete

br

app/views/chords/new.html.slim
h2 Добавить аккорд
== render 'form'

app/views/chords/show.html.slim
p#notice = notice

p
  strong Name:
  = @chord.name
p
  strong Sequence:
  = @chord.sequence
p
  strong Position:
  = @chord.position

= link_to 'Edit', edit_chord_path(@chord)
'  |
= link_to 'Back', chords_path