config/routes.rb
Rails.application.routes.draw do
  resources :chord_sequences
  resources :chords
  devise_for :users
  resources :tonalities

  root 'main#index'

  resources :api do
    collection do
      get :get_test_chords
      get :get_tonalities

      post :get_chords
      post :get_chords_new
    end
  end

end

app/models/tonality.rb
class Tonality < ActiveRecord::Base

  def stages
    @stages ||= self.sequence.mb_chars.downcase.split(',')
                    .each_with_index.map{|note_name, index| Stage.new(note_name, index + 1, self.offset)}
  end

  def get_stage(note_name)
    stages.find{|s|s.note_name == note_name.mb_chars.downcase[0..-2]}.index
  end
end

app/controllers/tonalities_controller.rb
class TonalitiesController < ApplicationController
  load_and_authorize_resource
  def index
    render :index
  end

  def new
    render :new
  end

  def create
    if @tonality.save
      redirect_to tonalities_path
    else
      render :new
    end
  end

  def update
    if @tonality.update_attributes(tonality_params)
      redirect_to tonalities_path
    else
      render :edit
    end
  end

  def destroy
    @tonality.destroy
    redirect_to tonalities_path
  end

  private

  def tonality_params
    params.require(:tonality).permit(:name, :sequence, :is_major, :offset)
  end
end

app/helpers/tonalities_helper.rb
module TonalitiesHelper
end

app/views/tonalities/_form.html.slim
#add-item action=""
  = simple_form_for [@tonality] do |t|
    .row
      .col-md-6
        .form-group
          = t.input :name, label: false, inner_html: {:placeholder => 'Наименование тональности', :class => 'form-control'}
        .form-group
          = t.input :sequence, label: false, inner_html: {:placeholder => 'Последовательность нот', :class => 'form-control'}
        .form-group
          = t.collection_radio_buttons :is_major,
                  [[true, 'Мажорная'] ,[false, 'Минорная']],
                  :first,
                  :last,
                  :item_wrapper_class => 'radio-inline'
        .form-group
          = t.input :offset, label: 'Смещение относительно До', inner_html: {:class => 'form-control'}
        .btn-group
          = t.submit 'Сохранить', class: 'submit'

app/views/tonalities/edit.html.slim
section#cabinet
  h1.title.container Редактирование тональности
  .container
    p = render 'form'

app/views/tonalities/index.html.slim
div.row
  div.col-xs-12
    div.box
      div.box-header
        h3.box-title Тональности
        div.box-tools
          = link_to 'Создать', new_tonality_path, :class => 'btn btn-primary'

      div.box
        .box-body.table-responsive.no-padding
          table.table.table-hover
            tbody
              tr
                th ID
                th Наименование
                th Последовательность
                th Мажор/Минор
                th Смещение относительно До
            - @tonalities.each do |t|
              tr
                td = t.id
                td = link_to t.name, edit_tonality_path(t)
                td = t.sequence
                td = t.is_major ? 'Мажор' : 'Минор'
                td = t.offset

app/views/tonalities/new.html.slim
h2 Добавить тональность
= render 'form'