config/routes.rb
Rails.application.routes.draw do
  resources :chord_sequences
  resources :chords
  devise_for :users
  resources :tonalities

  root 'main#index'

  resources :api do
    collection do
      get :get_test_chords
      get :get_tonalities

      post :get_chords
      post :get_chords_new
    end
  end

end

app/models/chord_sequence.rb
class ChordSequence < ActiveRecord::Base
  belongs_to :first_chord, class_name: "Chord"
  belongs_to :second_chord, class_name: "Chord"
  belongs_to :third_chord, class_name: "Chord"
  belongs_to :fourth_chord, class_name: "Chord"

  def self.get_sequences_for_chord(chord, is_json=false)
    # Если аккорд - функция, то ищем для него, иначе смотрим функцию
    parent_id = is_json ? chord["parent_chord_id"] : chord.parent_chord_id
    chord_id = is_json ? chord["id"] : chord.id

    result_chord_id = parent_id.nil? ? chord_id : parent_id
    ChordSequence.where(:first_chord_id => result_chord_id).order(fourth_chord_id: :desc, third_chord_id: :desc, second_chord_id: :desc).to_a
  end

  def get_indexes(prepared_chords, chord_position=false)
    result = []
    puts "#{self.as_json}"
    return [] if prepared_chords.length < self.to_array.length - 1
    prepared_chords.each_with_index do |chords, i|
      sequence_chord = self.to_array[i+1]
      # index = chords.find_index{|c|c.id == sequence_chord or c.parent_chord_id == sequence_chord}

      indexes = chords.size.times.
          select {|i|
        is_chord = (chords[i]["id"] == sequence_chord or chords[i]["parent_chord_id"] == sequence_chord)
        is_position = ((self.position and (chords[i]["position"] == chord_position)) or not self.position)
        puts "#{chords[i].as_json}, #{is_chord}, #{is_position}"
        is_chord and is_position
      }

      return [] if indexes.empty?
      result << indexes
    end
    # Если self.to_array.length == 2, то мы возвращаем [ [1], [2], [3] ]
    # return result if self.to_array.length == 2
    # Если self.to_array.length == 2, то мы возвращаем [ [1, 4], [1, 5], [2, 5], [3, 6] ]

    result
  end

  def self.get_all_sequences
    ChordSequence.all.order(fourth_chord_id: :desc, third_chord_id: :desc, second_chord_id: :desc).map{|c|{:chords => c.to_array, :position => c.position}}
  end

  def to_array
    result = []
    result << self.first_chord_id
    result << self.second_chord_id unless self.second_chord_id.nil?
    result << self.third_chord_id unless self.third_chord_id.nil?
    result << self.fourth_chord_id unless self.fourth_chord_id.nil?
    result
  end
end

app/controllers/chord_sequences_controller.rb
class ChordSequencesController < ApplicationController
  load_and_authorize_resource
  before_action :set_chords

  def index
    @chord_sequences = ChordSequence.order(:first_chord_id, :second_chord_id, :third_chord_id)
    render :index
  end

  def new
    render :new
  end

  def create
    if @chord_sequence.save
      redirect_to chord_sequences_path
    else
      render :new
    end
  end

  def update
    if @chord_sequence.update_attributes(chord_sequence_params)
      redirect_to chord_sequences_path
    else
      render :edit
    end
  end

  def destroy
    @chord_sequence.destroy
    redirect_to chord_sequences_path
  end

  private
    def set_chords
      @chords = Chord.where(:parent_chord_id => nil)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chord_sequence_params
      params.require(:chord_sequence).permit(:first_chord_id, :second_chord_id, :third_chord_id, :fourth_chord_id, :position)
    end
end

app/helpers/chord_sequences_helper.rb
module ChordSequencesHelper
end

app/views/chord_sequences/_form.html.slim
= simple_form_for(@chord_sequence, :defaults => { :input_html => { :class => "form-control" } }) do |f|
  - if @chord_sequence.errors.any?
    #error_explanation
      h2 = "#{pluralize(@chord_sequence.errors.count, "error")} prohibited this chord_sequence from being saved:"
      ul
        - @chord_sequence.errors.full_messages.each do |message|
          li = message
  .row
    .col-md-6
      .form-group
        = f.input :first_chord_id, :collection => @chords,  label: 'Первый аккорд'
      .form-group
        = f.input :second_chord_id, :collection => @chords,  label: 'Второй аккорд'
      .form-group
        = f.input :third_chord_id, :collection => @chords,  label: 'Третий аккорд'
      .form-group
        = f.input :fourth_chord_id, :collection => @chords,  label: 'Четвертый аккорд'
      .form-group
        = f.collection_radio_buttons :position,
                [[true, 'Имеет значение'], [false, 'Не имеет значения']],
                :first,
                :last,
                :item_wrapper_class => 'radio-inline'
      .btn-group
          = f.submit 'Сохранить', :class => 'btn btn-primary'
          = link_to 'Назад', chord_sequences_path, :class => 'btn btn-default'

app/views/chord_sequences/edit.html.slim
h1 Редактирование последовательности аккордов

== render 'form'

app/views/chord_sequences/index.html.slim
h1 Последовательности аккордов

= link_to 'Новая последовательность', new_chord_sequence_path
table.table
  thead
    tr
      th Первый аккорд
      th Второй аккорд
      th Третий аккорд
      th Четвертый аккорд
      th
      th

  tbody
    - @chord_sequences.each do |chord_sequence|
      tr
        td = chord_sequence.first_chord.try(:name)
        td = chord_sequence.second_chord.try(:name)
        td = chord_sequence.third_chord.try(:name)
        td = chord_sequence.fourth_chord.try(:name)
        td = link_to 'Редактировать', edit_chord_sequence_path(chord_sequence)
        td = link_to 'Удалить', chord_sequence, data: { confirm: 'Вы уверены?' }, method: :delete

br

app/views/chord_sequences/new.html.slim
h1 Добавить последовательность аккордов
== render 'form'

app/views/chord_sequences/show.html.slim
p#notice = notice

p
  strong First chord:
  = @chord_sequence.first_chord
p
  strong Second chord:
  = @chord_sequence.second_chord
p
  strong Third chord:
  = @chord_sequence.third_chord

= link_to 'Edit', edit_chord_sequence_path(@chord_sequence)
'  |
= link_to 'Back', chord_sequences_path